/* format
{
  name: "",
  course: "",     // 저널명 / 특허 패밀리 / arXiv 등
  detail: "",     // 권(호), 페이지, 번호 등
  year: 2026,
  authors: "",
  type: "",       // "sci" | "non-sci" | "patent"
  link: "",
}
*/

const members = [
  {
    name: "Se-Um Kim",
    status: "current",
    role: "Associate Professor",
    email: "seumkim@seoultech.ac.kr",
    phone: "+82-2-970-6425", office: "Mirae-Hall Unit 523",
    joinYear: 2022, leaveYear: null,
    image: "",
    description: "",
    slug: "s-ukim",
  },
  {
    name: "Hyeon Seong Hwang",
    status: "current",
    role: "Graduate",
    email: "he9312@seoultech.ac.kr",
    phone: "", office: "",
    joinYear: 2023, leaveYear: null,
    image: "",
    description: "",
    slug: "hshwang",
  },
  {
    name: "Hyo Seok Oh",
    status: "current",
    role: "Graduate",
    email: "ohs07@naver.com",
    phone: "", office: "",
    joinYear: 2024, leaveYear: null,
    image: "",
    description: "",
    slug: "hsoh",
  },
  {
    name: "Minhye Kim",
    status: "current",
    role: "Graduate",
    email: "minhyeral14@seoultech.ac.kr",
    phone: "", office: "",
    joinYear: 2025, leaveYear: null,
    image: "",
    description: "",
    slug: "mkim",
  },
  {
    name: "Min Ji Kim",
    status: "current",
    role: "Undergraduate",
    email: "kimminji0624@seoultech.ac.kr",
    phone: "", office: "",
    joinYear: 2024, leaveYear: null,
    image: "",
    description: "",
    slug: "mjkim",
  },
  {
    name: "Sangbaek Lee",
    status: "current",
    role: "Undergraduate",
    email: "sangbaek62@gmail.com",
    phone: "", office: "",
    joinYear: 2024, leaveYear: null,
    image: "",
    description: "",
    slug: "slee",
  },
  {
    name: "Sunjae Lee",
    status: "former",
    role: "Undergraduate",
    email: "ddwd1473@naver.com",
    phone: "", office: "",
    joinYear: 2024, leaveYear: null,
    image: "",
    description: "",
    slug: "slee2",
  },
  {
    name: "Doyo Kim",
    status: "current",
    role: "Undergraduate",
    email: "doyoo0413@seoultech.ac.kr",
    phone: "", office: "",
    joinYear: 2024, leaveYear: null,
    image: "",
    description: "",
    slug: "dkim",
  },
  {
    name: "Ae Bin Na",
    status: "current",
    role: "Undergraduate",
    email: "nab5191@naver.com",
    phone: "", office: "",
    joinYear: 2024, leaveYear: null,
    image: "",
    description: "",
    slug: "abna",
  },
  {
    name: "Hyun Jin Ko",
    status: "current",
    role: "Undergraduate",
    email: "hynnk77@seoultech.ac.kr",
    phone: "", office: "",
    joinYear: 2024, leaveYear: null,
    image: "",
    description: "",
    slug: "hjko",
  },
  {
    name: "Ji Hwan Kim",
    status: "current",
    role: "Undergraduate",
    email: "dyne0822@gmail.com",
    phone: "", office: "",
    joinYear: 2024, leaveYear: null,
    image: "",
    description: "",
    slug: "jhkim",
  },
  {
    name: "Hyeon Su Kim",
    status: "current",
    role: "Undergraduate",
    email: "khs1273@naver.com",
    phone: "", office: "",
    joinYear: 2024, leaveYear: null,
    image: "",
    description: "",
    slug: "hskim",
  },
  {
    name: "Hyeon Su Kim",
    status: "current",
    role: "Undergraduate",
    email: "khs1273@naver.com",
    phone: "", office: "",
    joinYear: 2024, leaveYear: null,
    image: "",
    description: "",
    slug: "hskim",
  },
];
