/* format
*/

const members = [
  {
    name: "Se-Um Kim",
    status: "current",
    role: "Associate Professor",
    email: "seumkim@seoultech.ac.kr",
    phone: "+82-2-970-6425", office: "Mirae-Hall Unit 523",
    joinYear: 2022, leaveYear: null,
    image: "",
    description: "",
    slug: "s-ukim",
  },
  {
    name: "I Hyeon Choi",
    status: "current",
    role: "Undergraduate",
    email: "yihyeonchoi11@gmail.com",
    phone: "", office: "",
    joinYear: 2026, leaveYear: null,
    image: "",
    description: "",
    slug: "ihchoi",
  },
  {
    name: "Minhye Kim",
    status: "current",
    role: "Graduate",
    email: "minhyeral14@seoultech.ac.kr",
    phone: "", office: "",
    joinYear: 2025, leaveYear: null,
    image: "",
    description: "",
    slug: "mkim",
  },
  {
    name: "Hyeon Su Kim",
    status: "current",
    role: "Undergraduate",
    email: "khs1273@naver.com",
    phone: "", office: "",
    joinYear: 2025, leaveYear: null,
    image: "",
    description: "",
    slug: "hskim",
  },
  {
    name: "Doyo Kim",
    status: "current",
    role: "Undergraduate",
    email: "doyoo0413@seoultech.ac.kr",
    phone: "", office: "",
    joinYear: 2025, leaveYear: null,
    image: "",
    description: "",
    slug: "dkim",
  },
  {
    name: "Ae Bin Na",
    status: "current",
    role: "Undergraduate",
    email: "nab5191@naver.com",
    phone: "", office: "",
    joinYear: 2025, leaveYear: null,
    image: "",
    description: "",
    slug: "abna",
  },
  {
    name: "Hyun Jin Ko",
    status: "current",
    role: "Undergraduate",
    email: "hynnk77@seoultech.ac.kr",
    phone: "", office: "",
    joinYear: 2025, leaveYear: null,
    image: "",
    description: "",
    slug: "hjko",
  },
  {
    name: "Min Ji Kim",
    status: "current",
    role: "Undergraduate",
    email: "kimminji0624@seoultech.ac.kr",
    phone: "", office: "",
    joinYear: 2024, leaveYear: null,
    image: "",
    description: "",
    slug: "mjkim",
  },
  {
    name: "Sangbaek Lee",
    status: "current",
    role: "Undergraduate",
    email: "sangbaek62@gmail.com",
    phone: "", office: "",
    joinYear: 2024, leaveYear: null,
    image: "",
    description: "",
    slug: "slee",
  },
  {
    name: "Sunjae Lee",
    status: "former",
    role: "Undergraduate",
    email: "ddwd1473@naver.com",
    phone: "", office: "",
    joinYear: 2024, leaveYear: 2025,
    image: "",
    description: "",
    slug: "slee2",
  },
  {
    name: "Ji Hwan Kim",
    status: "current",
    role: "Undergraduate",
    email: "dyne0822@gmail.com",
    phone: "", office: "",
    joinYear: 2024, leaveYear: null,
    image: "",
    description: "",
    slug: "jhkim",
  },
  {
    name: "Hyo Seok Oh",
    status: "current",
    role: "Graduate",
    email: "ohs07@naver.com",
    phone: "", office: "",
    joinYear: 2024, leaveYear: null,
    image: "",
    description: "",
    slug: "hsoh",
  },
  {
    name: "Hui Jun Jang",
    status: "former",
    role: "Graduate",
    email: "",
    phone: "", office: "",
    joinYear: 2024, leaveYear: 2025,
    image: "",
    description: "",
    slug: "hjjang",
  },
  {
    name: "Yong Jin Hwang",
    status: "former",
    role: "Undergraduate",
    email: "",
    phone: "", office: "",
    joinYear: 2023, leaveYear: 2025,
    image: "",
    description: "",
    slug: "yjhwang",
  },
  {
    name: "Hyeon Seong Hwang",
    status: "current",
    role: "Graduate",
    email: "he9312@seoultech.ac.kr",
    phone: "", office: "",
    joinYear: 2023, leaveYear: null,
    image: "",
    description: "",
    slug: "hshwang",
  },
  {
    name: "Hyun Mok Cho",
    status: "former",
    role: "Undergraduate",
    email: "",
    phone: "", office: "",
    joinYear: 2023, leaveYear: 2025,
    image: "",
    description: "",
    slug: "hmcho",
  },
  {
    name: "Jun Ho Lee",
    status: "former",
    role: "Undergraduate",
    email: "",
    phone: "", office: "",
    joinYear: 2023, leaveYear: 2024,
    image: "",
    description: "",
    slug: "jhlee",
  },
  {
    name: "Jung Eum Lee",
    status: "former",
    role: "Undergraduate",
    email: "",
    phone: "", office: "",
    joinYear: 2023, leaveYear: 2024,
    image: "",
    description: "",
    slug: "jelee",
  },
  {
    name: "Min-Seok Park",
    status: "former",
    role: "Undergraduate",
    email: "",
    phone: "", office: "",
    joinYear: 2022, leaveYear: 2023,
    image: "",
    description: "",
    slug: "m-spark",
  }
];
